### ISSUE TITLE
Issue with current version of docker?

### ISSUE THREAD

**Issue by sardaukar** [luxifer/dokku-redis-plugin#21]
I get this after installing this plugin and doing a rebuild of an app:

<pre>
-----> Releasing node-js-app ...

Usage: docker inspect CONTAINER|IMAGE [CONTAINER|IMAGE...]

Return low-level information on a container/image

  -format="": Format the output using the given go template.

-----> node-js-app linked to redis/node-js-app container
</pre>

I'm using Docker 0.7.6

**Comment by luxifer** [comment]
I'm sorry to reply so lately, this plugin has been deprecated, please use https://github.com/dokku/dokku-redis-plugin
