### ISSUE TITLE
On reboot new IP is assigned and redis need to be relinked

### ISSUE THREAD

**Issue by ernesto-jimenez** [luxifer/dokku-redis-plugin#24]
See https://github.com/Kloadut/dokku-pg-plugin/issues/12#issuecomment-31529546 for a comment on how dokku-pg-plugin addessed this.

dokku-redis uses always the same port and changes the IP in REDIS_URL. dokku-pg uses the same IP and changes the port in DATABASE_URL (see: https://github.com/Kloadut/dokku-pg-plugin/blob/master/commands#L167)

**Comment by luxifer** [comment]
can you check if #40 fixes your problem?

**Comment by ernesto-jimenez** [comment]
@luxifer we stopped using dokku, maybe somebody else on the thread can give it a go.

**Comment by gcohen55** [comment]
It works on reboot here.

**Comment by luxifer** [comment]
Nice to here

Florent Viel

**Comment by luxifer** [comment]
I'm sorry to reply so lately, this plugin has been deprecated, please use https://github.com/dokku/dokku-redis-plugin
