### ISSUE TITLE
Pushing to dokku with dokku-redis-plugin fails (Permission denied)

### ISSUE THREAD

**Issue by simonmaddox** [luxifer/dokku-redis-plugin#26]
On `git push dokku dokku:master` (I'm trying dokku out on another branch of my app, and renaming the remote ebranch to `master`), I'm getting the following output:

```
...
-----> Discovering process types
       Procfile declares types -> web, worker
       Default process types for Ruby -> rake, console, web, worker
-----> Releasing <app> ...
remote: /var/lib/dokku/plugins/redis/commands: line 111: /home/dokku/<app>/ENV: Permission denied
To dokku@<host>:<app>
 ! [remote rejected] dokku -> master (pre-receive hook declined)
error: failed to push some refs to '<host>:<app>'
```

Any idea what's going wrong?  Line 111 of `commands` is:

``` bash
echo -e "$ENV_TEMP" | sed '/^$/d' | sort > $ENV_FILE
```

I've already run `dokku redis:create <app>` too. I'm running this on a DigitalOcean dokku droplet (the 1GB instance, if it makes a difference).

**Comment by luxifer** [comment]
I'm sorry to reply so lately, this plugin has been deprecated, please use https://github.com/dokku/dokku-redis-plugin
