### ISSUE TITLE
dokku redis:unlink

### ISSUE THREAD

**Issue by Prinzhorn** [luxifer/dokku-redis-plugin#27]
How do I unlink the redis container from my app? Because I can't remove the redis container.

```
dokku redis:delete www
b0b7a3a3028f
Error: Conflict, cannot delete 90bd00bd9e8f because the container b0b7a3a3028f is using it
2014/04/21 08:31:00 Error: failed to remove one or more images
```

**Comment by jacobmarshall** [comment]
Hey, I am getting this error. Though the container's the error message refers to, do not exist. I was wondering what the fix is/whether a fix was ever found.

Thanks.

**Comment by luxifer** [comment]
I'm sorry to reply so lately, this plugin has been deprecated, please use https://github.com/dokku/dokku-redis-plugin
