### ISSUE TITLE
dokku-redis exposed on 0.0.0.0 / public interface

### ISSUE THREAD

**Issue by lenada** [luxifer/dokku-redis-plugin#35]
The current version sets a port for the redis-container via the `-p` switch.
This leads to docker binding that port to 0.0.0.0 /eth0. 
For a development setup that seems convenient.
But not the best idea for more productive systems.
I tried to close down the port with iptables... but sunk some hours without success.
Therefore I recommend removing the -p from the commit script.
As linked containers get reported the docker IP anyway.

I have a "fixed" forked version here https://github.com/wesrc/dokku-redis-plugin/commit/101ce67006b1fc45ca924c807941c3dddac5a925 and can do a proper PR if wanted.

**Comment by loa** [comment]
Same issue

**Comment by luxifer** [comment]
I'm sorry to reply so lately, this plugin has been deprecated, please use https://github.com/dokku/dokku-redis-plugin
