### ISSUE TITLE
What happens at reboot?

### ISSUE THREAD

**Issue by nicola** [luxifer/dokku-redis-plugin#36]
1) Redis is never restarted
2) There is no way to restar redis unless I manually do the following:
```
ID=$(docker run -v $VOLUME -p 6379 -d $REDIS_IMAGE /bin/start_redis.sh)
```
for each project I have.

Is there a possibility to fix this problem?

**Comment by luxifer** [comment]
does #40 fixes your problem?

**Comment by luxifer** [comment]
I'm sorry to reply so lately, this plugin has been deprecated, please use https://github.com/dokku/dokku-redis-plugin
