### ISSUE TITLE
REDIS_PORT and REDIS_HOST don't match REDIS_URL

### ISSUE THREAD

**Issue by matthewmueller** [luxifer/dokku-redis-plugin#37]
`REDIS_PORT` and `REDIS_HOST` are wrong / not updated, while `REDIS_URL` is the correct info.

**Comment by mkly** [comment]
Does this PR address your issue? #39

**Comment by MatthewMueller** [comment]
not 100% sure, we have been avoiding `redis:link` because it wasn't really working.

**Comment by luxifer** [comment]
I'm sorry to reply so lately, this plugin has been deprecated, please use https://github.com/dokku/dokku-redis-plugin
