### ISSUE TITLE
Redis connect failed (connect ENOENT)

### ISSUE THREAD

**Issue by tomsoft1** [luxifer/dokku-redis-plugin#38]
I've created a container:

    dokku redis:create myapp

I'see the specific redis var:

    dokku config

    === myapp config vars ===
    REDIS_URL: redis://172.17.0.61:6379

But then, when I try to connect to the redis instance, I have the following error in the dokku logs:

    > node app.js
    Main stream starting
    Error Error: Redis connection to redis://172.17.0.38:6379 failed - connect ENOENT

the redis instance seems to be running ( a ps confirm it), but there is nothing in redis log...Any help appreciate, thanks in advance

**Comment by sekjun9878** [comment]
Please refer to this StackOverflow question: http://stackoverflow.com/questions/9939607/external-database-with-redis-connect

You should be using REDIS_HOST + REDIS_PORT instead of REDIS_URL

**Comment by luxifer** [comment]
I'm sorry to reply so lately, this plugin has been deprecated, please use https://github.com/dokku/dokku-redis-plugin
