### ISSUE TITLE
REDIS_URL=redis://redis:6379

### ISSUE THREAD

**Issue by martolini** [luxifer/dokku-redis-plugin#44]
This can't be right.

    dokku redis:create talkingdev
    -----> Redis database created: redis_app_talkingdev
    -----> Releasing talkingdev ...
    -----> Deploying talkingdev ...
    -----> Shutting down old containers
    =====> Application deployed:

**Comment by luxifer** [comment]
ow yes of course...

**Comment by martolini** [comment]
So I guess I'm missing something here.

**Comment by maxfrigge** [comment]
Could you please elaborate? Is dokku using some sort of host mapping for this, because my nodejs app gets this url and then tries to connect to localhost.. which fails.

`[Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379]`
