### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by hhff** [luxifer/dokku-redis-plugin#45]
Hi @luxifer !

Thankyou so much for this plugin!

I just installed it into my new Dokku v0.3.19 app, and found I had to make a few changes to get it working with the new version of Docker that it ships with.

Is this plugin still maintained?  I'd be happy to help out with it?

**Comment by luxifer** [comment]
If you want to help you are welcome. You can submit a PR with your changes
to work with the latest version of docker. I'll be happy to review it!

Florent Viel

**Comment by luxifer** [comment]
I'm sorry to reply so lately, this plugin has been deprecated, please use https://github.com/dokku/dokku-redis-plugin
