### ISSUE TITLE
redis:link produce wrong url after system restart

### ISSUE THREAD

**Issue by roma86** [luxifer/dokku-redis-plugin#46]
Hello. thank you for plugin. 

> Ubuntu 14.04
> dokku v0.3.16
> dokku-redis-plugin installed from readme instructions (no release versioning)

After first installation application linked with error: 

```bad URI(is not URI?): redis://174.17.0.44 174.17.0.44:6379 (URI::InvalidURIError)```

dancing with a tambourine, restart app, stop/start redis container directly with docker – :link command get me right url redis://174.17.0.44:6379$ (Dollar dollar sign on the end? hmmm, strange... but rails parse url correctly and accept).

Day later, server was restarted – link broken again. 
In this time only manual dokku config:set REDIS_URL allow me run my application linked with redis. 

What i am doing wrong?

**Comment by roma86** [comment]
Also. 
I think you can say: Hey! Use REDIS_IP + REDIS_PORT to build REDIS_URL manually.
O`k, i try, but generated REDIS_IP variable is not correct

```bash
dokku config app_name
=====> app_name config vars
DATABASE_URL: postgres://root:*****@174.17.44.1:49154/db
REDIS_IP:     174.17.0.44 174.17.0.44
REDIS_PORT:   6379
REDIS_URL:    redis://174.17.0.44 174.17.0.44:6379
```

**Comment by luxifer** [comment]
I'm sorry to reply so lately, this plugin has been deprecated, please use https://github.com/dokku/dokku-redis-plugin
