### ISSUE TITLE
Error deleting

### ISSUE THREAD

**Issue by cristobalcl** [luxifer/dokku-redis-plugin#47]
I created a container with the same name of the app. It worked. Then I tried delete it but I get this error:

```
76e6050a9e7f
Error response from daemon: Conflict, cannot delete 13d9c76a1d02 because the container 76e6050a9e7f is using it, use -f to force
FATA[0000] Error: failed to remove one or more images
```

I stopped the app and tried again and got the same error. Finally I did:

```
sudo docker rmi -f redis/demo
sudo dokku redis:delete demo
```

And all seems ok now. It could be a docker's problem.

**Comment by AlJohri** [comment]
This plugin is deprecated. Use https://github.com/dokku/dokku-redis instead.

**Comment by cristobalcl** [comment]
Ok, thank you very much!

**Comment by luxifer** [comment]
thanks @AlJohri
